server:
  port: 3333
  servlet:
    context-path: /devweek

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://pwwrwyxtstunxh:7380e9c3019401083fc36ac8f159fb66bfeefbb1c56d93dc26709ece9b354558@ec2-184-73-198-174.compute-1.amazonaws.com:5432/d4vpcs5i5qboiv
    username: pwwrwyxtstunxh
    password: 7380e9c3019401083fc36ac8f159fb66bfeefbb1c56d93dc26709ece9b354558
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a devweek DIO - Santander